### ISSUE TITLE
What is rb?

### ISSUE THREAD

**Issue by millionfor** [allex/rollup-worker#1]
What is rb? 
rollup-worker@1.0.9-beta.2 build: `rb -c && shx chmod a+x bin/cli.js`

**Comment by allex** [comment]
> What is rb?
> rollup-worker@1.0.9-beta.2 build: `rb -c && shx chmod a+x bin/cli.js`

Actually, `rb` is this project cli it self. you can install it by `npm i rollup-worker -g`.
